### ISSUE TITLE
Unable to push code

### ISSUE THREAD

**Issue by geoand** [cmoulliard/k8s-supervisor#2]
Following the instructions, I have successfully started the application as can seen in the following image:

![supervisor](https://user-images.githubusercontent.com/4374975/42639014-ba6c823a-85f7-11e8-9976-8cb61a226ee6.jpg)

However when I follow the instructions to push code by executing:

```bash
SB_POD=$(oc get pods -l app=spring-boot-supervisord -o name)

oc rsh $SB_POD /var/lib/supervisord/bin/supervisord ctl status
```

I get the following error:

```
Fail to send request to supervisord: Post http://localhost:9001/RPC2: dial tcp [::1]:9001: connect: connection refused
```

I am guessing the problem is that the problem is that there is no supervisord configuration file as I discovered using the following commands:

```
oc exec -it $(oc get pods -l app=spring-boot-supervisord -o json | jq -r '.items[0] | .metadata.name') bash
ls -l /var/lib/supervisord/conf

total 12
-rwxr-xr-x 1 1000080000 1000080000  32 Jul 12 14:17 echo.sh
-rw-r--r-- 1 1000080000 1000080000 236 Jul 12 14:17 supervisor-local.conf
-rw-r--r-- 1 1000080000 1000080000 250 Jul 12 14:17 supervisord.tmpl
```

**Comment by cmoulliard** [comment]
I have pushed a new image on quay and changed the initContainer's script to launch it. This is fixed

**Comment by geoand** [comment]
Sounds good!
